// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://gp5667xei5hpbix2632i4zivhe.appsync-api.eu-north-1.amazonaws.com/graphql',
          region: 'us-east-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-unnf7mgb7zgermwvwmurptnvvm'
        }
    }
};

export default config;
